<?php
/**
 * Softnoesis
 * Copyright(C) 21/2022 Softnoesis <contact@softnoesis.com>
 * @package Softnoesis_ProductBrand
 * @copyright Copyright(C) 2015 Softnoesis (contact@softnoesis.com)
 * @author Softnoesis <contact@softnoesis.com>
 */
?>
<?php $_product = $block->getProduct();
    $entity_id = $_product->getId();
    $load = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $load->create('Magento\Catalog\Model\Product')->load($entity_id);
    $manufacture = $product->getAttributeText('manufacturer');
if ($manufacture != '') {?>
                <div class="product-brand">
                    <b><?php echo $manufacture;?></b>
                </div>
<?php }?>